"""
Written by KrishPro @ KP

NOTE: DONT CHANGE ANYTHING, UNLESS YOU KNOW WHAT YOU'RE DOING !!
"""

EPOCHS = 40
LEARNING_RATE = 3e-4
EMBED_SIZE = 128
BATCH_SIZE = 32
HIDDEN_SIZE = 256
N_LAYERS = 2
SEQ_LEN = 250